# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push]
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
   # branches: [ main ]
  #pull_request:
   # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    strategy: 
      matrix:
        node_version: [10,12]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Use Node.js ${{matrix.node_version }}
        uses: actions/setup-node@v1
        with: 
          version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      # Runs a set of commands using the runners shell
      - name: yarn install, yarn lint, yarn test, yarn build
        run: |
          yarn install
          yarn lint
          yarn test
          yarn build
